apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  AUTH_SVC_ADDRESS: "auth:5000"
  MONGODG_VIDEOS_URI: "mongodb://lucas:lucas1234@mongodb:27017/videos?authSource=admin"
  GODB_MP3_URI: "mongodb://lucas:lucas1234@mongodb:27017/mp3s?authSource=admin"