#Imperative command to create service to expose api deployment
#kubectl expose deploy api \ --name=api \ --type=LoadBalancer \ port=80 \ --target-port=8080
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer