apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: learnDevOps
  labels:
    role: db
    env: demo
spec:
  selector:
    role: db
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: none